### ISSUE TITLE
Where is the tei_skeleton.xml file and What kind of file is this?

### ISSUE THREAD

**Issue by tboenig** [wrznr/mets-mods2teiHeader#11]
Hi @wrznr,

where is the tei_skeleton.xml file. The system look for this files in:
``/.../mets-mods2teiHeader/env/lib/python3.5/site-packages/mets_mods2teiHeader/data/tei_skeleton.xml``
but it did'nt find them.
What kind of file is this?

**Comment by wrznr** [comment]
It's an XML file which serves as the skeleton for constructing a minimal TEI tree which is further extended in the conversion process. It should be installed in the correct place automatically (it is in my environment at least). Thanks for reporting. I will have a look into this.

**Comment by wrznr** [comment]
As a temporary work around, you may want to install with `pip`'s `-e` option.
